apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "roger-hello.fullname" . }}
  labels:
    {{- include "roger-hello.labels" . | nindent 4 }}
data:
  message_interval: {{ .Values.messageInterval | quote }}