apiVersion: v1
kind: Service
metadata:
  name: roger-hello
  labels:
    {{- include "roger-hello.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "roger-hello.selectorLabels" . | nindent 4 }}
